build:
  base: /
  command: npm run build
  publish: dist
  environment:
    NODE_VERSION: 18
    SKIP_RUBY: true
    SKIP_PYTHON: true
    RUBY_VERSION: false
    PYTHON_VERSION: false
    NODE_ENV: production
