[build]
  command = "npm install --platform=linux --arch=x64 && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
