[build]
  command = "npm run build"
  publish = "dist"
  base = "/"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  RUBY_ENABLED = "false"
  PYTHON_ENABLED = "false"
  USE_RUBY_VERSION = "false"
  USE_PYTHON_VERSION = "false"

[context.production]
  command = "npm install && npm run build"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
